[package]
name = "G4Patcher"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.27"
rfd = "0.15.3"
fs_extra = "1.3.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
